version: 2.1
orbs:
  architect: giantswarm/architect@6.7.0

workflows:
  build:
    jobs:
    - architect/go-build:
        context: architect
        name: go-build
        binary: release-exporter
        filters:
          tags:
            only: /^v.*/

    - architect/push-to-registries:
        context: architect
        name: push-to-registries
        requires:
        - go-build
        filters:
          tags:
            only: /^v.*/

          branches:
            ignore:
            - main
            - master
    - architect/push-to-app-catalog:
        context: architect
        requires:
        - push-to-registries
        name: push-to-app-catalog
        executor: app-build-suite
        app_catalog: giantswarm-operations-platform-catalog
        app_catalog_test: giantswarm-operations-platform-test-catalog
        chart: release-exporter
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
